name: ci

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  core:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6

    - run: echo $PATH

    - run: cmake --version

    - name: set macOS Gfortran
      if: runner.os == 'macOS'
      run: echo "FC=gfortran-15" >> $GITHUB_ENV

    - name: configure cmake (w/ Fortran)
      if: runner.os != 'Windows'
      run: cmake --workflow default

    - name: configure CMake (w/o Fortran)
      if: runner.os == 'Windows'
      run: cmake --workflow nofortran
